name: snowplow_flutter_tracker
description: Snowplow event tracker for Flutter. Add analytics to your Flutter apps and games
homepage: https://github.com/HomeXLabs/snowplow-flutter-tracker
version: 0.11.0

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.11.0

flutter:
  plugin:
    platforms:
      android:
        package: com.patricktailor.snowplow_flutter_tracker
        pluginClass: SnowplowFlutterTrackerPlugin
      ios:
        pluginClass: SnowplowFlutterTrackerPlugin